version: "3"
services:
  node:
    image: "node:12"
    user: "node"
    working_dir: /home/frontend/wpi-shortcode-builder
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    command: "npm run serve"
