version: "3"
services:
  container_name: my-app
  build:
    context: .
    dockerfile: Dockerfile

  volumes:
      - ./:/app
  ports:
      - 80:8080
  command: "npm run build -t media-store-net/shortcodebuilder ."
